configEnvs:
  CONFIG_A: example CONFIG_A
  CONFIG_B: example CONFIG_B
secretConfigEnvs:
  SECRET_A: example SECRET_A
  SECRET_B: example SECRET_B
configFiles:
  config.json: |
    {
      "data": "example config.json"
    }
secretConfigFiles:
  secret.json: |
    {
      "data": "example secret.json"
    }
